import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';

/**
 * Read TypeDoc's JSON and expose it in the shapes the reference components
 * need. The generator produces data; the pages are composed by hand.
 *
 * The file is gitignored and regenerated by `pnpm docs:api`. When it is
 * absent — a fresh clone, or someone working on unrelated site pages — this
 * warns once and returns empty rather than failing the build, so the site
 * never depends on having run the generator.
 */

interface Comment {
  summary?: Array<{ kind: string; text: string }>;
  blockTags?: Array<{ tag: string; content: Array<{ kind: string; text: string }> }>;
}

interface Reflection {
  id: number;
  name: string;
  kind: number;
  comment?: Comment;
  children?: Reflection[];
  signatures?: Reflection[];
  parameters?: Reflection[];
  type?: TypeNode;
  flags?: { isOptional?: boolean };
}

export interface TypeNode {
  type: string;
  name?: string;
  value?: unknown;
  types?: TypeNode[];
  elementType?: TypeNode;
  typeArguments?: TypeNode[];
  target?: TypeNode;
  declaration?: Reflection;
}

const KIND = {
  Module: 2,
  Enum: 8,
  Variable: 32,
  Function: 64,
  Class: 128,
  Interface: 256,
  Property: 1024,
  Method: 2048,
  TypeAlias: 2097152,
} as const;

let cached: Reflection | null | undefined;

function load(): Reflection | null {
  if (cached !== undefined) return cached;
  try {
    // resolved from the site root rather than import.meta.url: this module is
    // bundled at build time, so a URL relative to it no longer points at .data
    cached = JSON.parse(readFileSync(resolve(process.cwd(), '.data/api.json'), 'utf8')) as Reflection;
  } catch {
    console.warn('[api] site/.data/api.json absent — lance `pnpm docs:api`. La référence sera vide.');
    cached = null;
  }
  return cached;
}

const textOf = (parts: Array<{ text: string }> | undefined): string =>
  (parts ?? []).map((p) => p.text).join('').trim();

/** The first sentence — what lands in a Description cell. */
export function summary(r: Reflection | undefined): string {
  return textOf(r?.comment?.summary);
}

export function tag(r: Reflection | undefined, name: string): string | undefined {
  const found = r?.comment?.blockTags?.find((t) => t.tag === `@${name}`);
  return found ? textOf(found.content) : undefined;
}

export function tags(r: Reflection | undefined, name: string): string[] {
  return (r?.comment?.blockTags ?? []).filter((t) => t.tag === `@${name}`).map((t) => textOf(t.content));
}

/** Render a type node as the TypeScript a reader would write. */
export function typeText(t: TypeNode | undefined): string {
  if (!t) return 'unknown';
  switch (t.type) {
    case 'intrinsic':
    case 'reference': {
      const args = t.typeArguments?.length ? `<${t.typeArguments.map(typeText).join(', ')}>` : '';
      return `${t.name ?? 'unknown'}${args}`;
    }
    case 'literal':
      return typeof t.value === 'string' ? `'${t.value}'` : String(t.value);
    case 'union':
      return (t.types ?? []).map(typeText).join(' | ');
    case 'intersection':
      return (t.types ?? []).map(typeText).join(' & ');
    case 'array':
      return `${typeText(t.elementType)}[]`;
    case 'reflection':
      return t.declaration?.signatures?.length ? 'function' : 'object';
    default:
      return t.name ?? t.type;
  }
}

export interface Entry {
  name: string;
  /** `name?: Type` — type, optionality and required in one TS-shaped string. */
  signature: string;
  type: string;
  optional: boolean;
  summary: string;
  defaultValue?: string;
  remarks?: string;
  examples: string[];
  deprecated?: string;
  /** `#param-parent-child` — namespaced and path-aware, so nesting never collides. */
  anchor: string;
}

function toEntry(r: Reflection, prefix: string): Entry {
  const optional = r.flags?.isOptional === true;
  const type = typeText(r.type ?? r.signatures?.[0]?.type);
  const path = prefix ? `${prefix}-${r.name}` : r.name;
  return {
    name: r.name,
    signature: `${r.name}${optional ? '?' : ''}: ${type}`,
    type,
    optional,
    summary: summary(r),
    defaultValue: tag(r, 'defaultValue') ?? tag(r, 'default'),
    remarks: tag(r, 'remarks'),
    examples: tags(r, 'example'),
    deprecated: tag(r, 'deprecated'),
    anchor: `param-${path.toLowerCase()}`,
  };
}

function findModule(name: string): Reflection | undefined {
  return load()?.children?.find((c) => c.name === name);
}

function findIn(mod: Reflection | undefined, name: string): Reflection | undefined {
  return mod?.children?.find((c) => c.name === name);
}

/** Properties of an interface or type alias, as an options table. */
export function options(moduleName: string, typeName: string): Entry[] {
  const decl = findIn(findModule(moduleName), typeName);
  const members = decl?.children ?? decl?.type?.declaration?.children ?? [];
  return members
    .filter((m) => m.kind === KIND.Property || m.kind === KIND.Method)
    .map((m) => toEntry(m, typeName));
}

export interface MethodEntry {
  name: string;
  signature: string;
  summary: string;
  returns: string;
  params: Array<{ name: string; type: string; summary: string; optional: boolean }>;
  examples: string[];
  anchor: string;
}

/** Methods of a class, or standalone functions of a module. */
export function methods(moduleName: string, className?: string): MethodEntry[] {
  const mod = findModule(moduleName);
  const source = className ? findIn(mod, className)?.children : mod?.children;
  return (source ?? [])
    .filter((m) => m.kind === KIND.Method || m.kind === KIND.Function)
    .filter((m) => summary(m.signatures?.[0]) || summary(m))
    .map((m) => {
      const sig = m.signatures?.[0];
      const params = (sig?.parameters ?? []).map((p) => ({
        name: p.name,
        type: typeText(p.type),
        summary: summary(p),
        optional: p.flags?.isOptional === true,
      }));
      const returns = typeText(sig?.type);
      const args = params.map((p) => `${p.name}${p.optional ? '?' : ''}: ${p.type}`).join(', ');
      return {
        name: m.name,
        signature: `${m.name}(${args}): ${returns}`,
        summary: summary(sig) || summary(m),
        returns,
        params,
        examples: tags(sig, 'example'),
        anchor: `method-${m.name.toLowerCase()}`,
      };
    });
}

/** Everything a module exports that carries documentation, for an index. */
export function moduleIndex(moduleName: string): Array<{ name: string; kind: string; summary: string }> {
  const names: Record<number, string> = {
    [KIND.Function]: 'fonction',
    [KIND.Interface]: 'interface',
    [KIND.Class]: 'classe',
    [KIND.TypeAlias]: 'type',
    [KIND.Variable]: 'constante',
    [KIND.Enum]: 'énumération',
  };
  return (findModule(moduleName)?.children ?? [])
    .filter((c) => names[c.kind])
    .map((c) => ({
      name: c.name,
      kind: names[c.kind]!,
      summary: summary(c.signatures?.[0]) || summary(c),
    }))
    .sort((a, b) => a.name.localeCompare(b.name));
}

export function moduleSummary(moduleName: string): string {
  return summary(findModule(moduleName));
}

export const API_MODULES = ['@nbe/core', '@nbe/dom', '@nbe/markdown', '@nbe/static-renderer'] as const;
