import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { it } from 'vitest';
import { uuidv7 } from '@nbe/core';
import { LoroBlockStore } from '../src/store';

/**
 * Write the snapshot a second implementation is checked against.
 *
 * @remarks
 * Generated by the editor's own code rather than hand-written, for the same
 * reason `native/swift`'s JSON fixture is: a fixture an author typed proves
 * agreement with that author's idea of the format.
 */
it('writes the Swift interop snapshot', () => {
  const store = new LoroBlockStore();
  /*
   * A fixed peer id, so the bytes are the same on every run. Loro picks a
   * random one otherwise, and a fixture that changes every time it is checked
   * would leave a dirty tree after each test run and make its own diffs
   * unreadable.
   */
  store.doc.setPeerId(1n);
  const rootId = '01920000-0000-7000-8000-000000000001';
  store.set(rootId, { id: rootId, type: 'page', version: 1, props: { title: 'Interop' }, children: [], parentId: null });
  const child = '01920000-0000-7000-8000-000000000002';
  store.set(child, {
    id: child,
    type: 'paragraph',
    version: 1,
    props: {},
    children: [],
    parentId: rootId,
    text: [{ text: 'écrit par TypeScript' }],
  });
  store.set(rootId, { ...store.get(rootId)!, children: [child] });

  writeFileSync(
    join(__dirname, '..', '..', '..', 'native', 'swift', 'Tests', 'NbeModelTests', 'document.loro'),
    store.doc.export({ mode: 'snapshot' }),
  );
  void uuidv7;
});
